[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64", "setuptools-scm>=8"]

[tool.setuptools_scm]
root = "../../.."

[project]
name = "agentiq-test"
dynamic = ["version"]
dependencies = [
  "aiqtoolkit[test]~=1.1"
]
readme = "pypi.md"
description = "Transitional package for aiqtoolkit-test, this package is deprecated and will be removed in the future."
classifiers = ["Programming Language :: Python"]
